dist: trusty
sudo: required

language: php

php:
  - 7.4

before_script:
  - cp .env.travis .env
  - mysql -e 'create database crescendo_travis;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate

script:
  - vendor/bin/phpunit

notifications:
  email: false

deploy:
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    application: forte-api
    deployment_group: forte-api
    region: ap-northeast-2
